export class SabnzbdStatus {
  uptime: string | undefined;
  color_scheme: string | undefined;
  helpuri: string | undefined;
  restart_req: boolean | undefined;
  pid: number | undefined;
  active_lang: string | undefined;
  rtl: boolean | undefined;
  my_lcldata: string | undefined;
  my_home: string | undefined;
  webdir: string | undefined;
  url_base: string | undefined;
  nt: boolean | undefined;
  darwin: boolean | undefined;
  power_options: boolean | undefined;
  pp_pause_event: boolean | undefined;
  apikey: string | undefined;
  new_release: string | undefined;
  new_rel_url: string | undefined;
  version: string | undefined;
  paused: boolean | undefined;
  pause_int: string | undefined;
  paused_all: boolean | undefined;
  diskspace1: string | undefined;
  diskspace2: string | undefined;
  diskspace1_norm: string | undefined;
  diskspace2_norm: string | undefined;
  diskspacetotal1: string | undefined;
  diskspacetotal2: string | undefined;
  loadavg: string | undefined;
  speedlimit: string | undefined;
  speedlimit_abs: string | undefined;
  have_warnings: string | undefined;
  finishaction: any | undefined;
  quota: string | undefined;
  have_quota: boolean | undefined;
  left_quota: string | undefined;
  cache_art: string | undefined;
  cache_size: string | undefined;
  cache_max: string | undefined;
  logfile: string | undefined;
  weblogfile: any | undefined;
  loglevel: string | undefined;
  folders: string[] | undefined;
  configfn: string | undefined;
  warnings: any[] | undefined;
  cpumodel: string | undefined;
  pystone: number | undefined;
  downloaddir: string | undefined;
  downloaddirspeed: number | undefined;
  completedir: string | undefined;
  completedirspeed: number | undefined;
  internetbandwidth: number | undefined;
  servers: Server[] | undefined;
}

export interface Server {
  servername: string;
  serveractiveconn: number;
  servertotalconn: number;
  serverconnections: any[];
  serverssl: number;
  serversslinfo: string;
  serveractive: boolean;
  servererror: string;
  serverpriority: number;
  serveroptional: number;
  serverbps: string;
}
